### ISSUE TITLE
Assets/Fotos zentrierbar machen?

### ISSUE THREAD

**Issue by happy-yoga** [happy-yoga/hy-web#10]
Sind alle Fotos aus Überzeugung linksbündig, ohne daß ich das ändern kann? Hier sähe das Herz oder Logo z.B. schöner irgendwo zentriert aus: https://hy-web-preview.herokuapp.com/pages/anusara-page

**Comment by mechanoid** [comment]
Ich finde das definitiv auch besser. Schaue ich mir an. Bitte achte bei dem Bild (ist mir hier gerade aufgefallen) drauf, dass du ne gute Auflösung nimmst. Das Herzchen Bild ist lowres und wirkt sehr aufgeschwemmt :/

**Comment by mechanoid** [comment]
Du kannst nun, anstatt ein Bild direkt hinzuzufügen, erst einen Text Image Container hinzufügen, und in dem ein Bild und eine "direction" angeben. Um ein Bild links, mittig oder rechts auszurichten.

<img width="799" alt="Screenshot 2023-04-08 at 18 58 49" src="https://user-images.githubusercontent.com/1382108/230733796-2b4aed1c-631e-4b67-a797-fa243b29b5a3.png">

Für jedes Bild dann einen neuen Container anlegen, dort kannst du dann die Ausrichtung wählen.

<img width="785" alt="Screenshot 2023-04-08 at 19 01 09" src="https://user-images.githubusercontent.com/1382108/230733856-70b9a688-ff42-4d72-98ff-bdcaab80a597.png">
