### ISSUE TITLE
Transparente Headline Startseiten-Teaser

### ISSUE THREAD

**Issue by happy-yoga** [happy-yoga/hy-web#2]

**Comment by happy-yoga** [comment]
Wird bei mir in Chrome nicht angezeigt

**Comment by happy-yoga** [comment]
@mechanoid Ist immer noch relativ schlecht zu lesen, oder?

**Comment by mechanoid** [comment]
ja, im Chrome ist das immernoch mies, ich schaue noch wie ich das am besten handhabe ohne es ganz zu deaktivieren

**Comment by happy-yoga** [comment]
Hast Du jetzt eine Benachrichtigung bekommen, weil ich Dich erwähnt habe?

**Comment by mechanoid** [comment]
nee brauchst du nicht, ich hab die Einstellungen geändert
