### ISSUE TITLE
Footer Email

### ISSUE THREAD

**Issue by happy-yoga** [happy-yoga/hy-web#5]
Meine Email ist info@happyyoga.de - zusammengeschrieben!
Kann ich den Footer selbst nicht ändern? Hab ich nicht gefunden, sorry.

**Comment by happy-yoga** [comment]
@mechanoid :-)

**Comment by mechanoid** [comment]
done :) https://app.contentful.com/spaces/joqqoffik2q2/entries/7Be0GBNcGEGgFxDNUi23CG
